CREATE DATABASE IF NOT EXISTS wuery;

CREATE TABLE IF NOT EXISTS wuery.all_types (
    t_bool BOOL DEFAULT true,
    t_boolean BOOLEAN DEFAULT false,
    t_bytes BYTES DEFAULT b'\x61\x62\x63',
    t_bytea BYTEA DEFAULT b'\141\x62\c',
    t_blob BLOB DEFAULT b'abc',
    t_date DATE DEFAULT '2016-03-26',
    t_decimal DECIMAL DEFAULT 1.01234567890123456789,
    t_dec DEC DEFAULT 1.01234567890123456789,
    t_numeric NUMERIC DEFAULT 1.01234567890123456789,
    t_float FLOAT DEFAULT 1.012345678901,
    t_real REAL DEFAULT 2.01234567890123456789,
    t_float4 FLOAT4 DEFAULT 2.01234567890123456789,
    t_double_precision DOUBLE PRECISION DEFAULT CAST('+Inf' AS FLOAT),
    t_float8 FLOAT8 DEFAULT CAST('+Inf' AS FLOAT),
    t_inet INET DEFAULT '2001:4f8:3:ba:2e0:81ff:fe22:d1f1/120',
    t_int INT DEFAULT 1,
    t_integer INTEGER DEFAULT 1,
    t_int8 INT8 DEFAULT 1,
    t_int64 INT64 DEFAULT 1,
    t_bigint BIGINT DEFAULT 1,
    t_int4 INT4 DEFAULT 1,
    t_int2 INT2 DEFAULT 1,
    t_smallint SMALLINT DEFAULT 1,
    t_bit BIT DEFAULT 1,
    t_bit_2 BIT(2) DEFAULT 1,
    t_interval INTERVAL DEFAULT '1h2m3s4ms5us6ns',
    t_jsonb JSONB DEFAULT '{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}',
    t_json JSON DEFAULT '{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}',
    t_serial SERIAL,
    t_serial2 SERIAL2,
    t_serial4 SERIAL4,
    t_serial8 SERIAL8,
    t_smallserial SMALLSERIAL,
    t_bigserial BIGSERIAl,
    t_time TIME DEFAULT '05:40:00',
    t_time_without_time_zone TIME WITHOUT TIME ZONE DEFAULT '05:40:00',
    t_timestampz TIMESTAMPTZ DEFAULT (TIMESTAMPTZ '2016-03-26 15:10:10+70:00'),
    t_timestamp_with_time_zone TIMESTAMP WITH TIME ZONE DEFAULT (TIMESTAMPTZ '2016-03-26 15:10:10+00:00'),
    t_timestamp TIMESTAMP DEFAULT (TIMESTAMP '2016-01-25 10:10:10.555555'),    
    t_timestamp_without_time_zone TIMESTAMP WITHOUT TIME ZONE DEFAULT (TIMESTAMP '2016-01-25 10:10:10.555555'),
    t_uuid UUID DEFAULT gen_random_uuid(),
    t_string STRING DEFAULT 'a',
    t_character CHARACTER DEFAULT 'a',
    t_char CHAR DEFAULT 'a',
    t_varchar VARCHAR DEFAULT 'a',
    t_text TEXT DEFAULT 'a',
    t_string_n STRING(1) DEFAULT 'a',
    t_character_n CHARACTER(2) DEFAULT 'a',
    t_char_n CHAR(3) DEFAULT 'a',
    t_varchar_n VARCHAR(4) DEFAULT 'a',
    t_string_collate STRING COLLATE de DEFAULT ('Bar' COLLATE de),
    t_character_collate CHARACTER COLLATE de DEFAULT ('Bar' COLLATE de),
    t_char_collate CHAR COLLATE de DEFAULT ('Bar' COLLATE de),
    t_varchar_collate VARCHAR COLLATE de DEFAULT ('Bar' COLLATE de),
    t_text_collate TEXT COLLATE de DEFAULT ('Bar' COLLATE de),
    t_string_n_collate STRING(1) COLLATE de DEFAULT ('Bar' COLLATE de),
    t_character_n_collate CHARACTER(2) COLLATE de DEFAULT ('Bar' COLLATE de),
    t_char_n_collate CHAR(3) COLLATE de DEFAULT ('Bar' COLLATE de),
    t_varchar_n_collate VARCHAR(4) COLLATE de DEFAULT ('Bar' COLLATE de)
);